PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcmitype: <http://purl.org/dc/dcmitype/>
PREFIX ebucore: <https://www.ebu.ch/metadata/ontologies/ebucore#>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX bsd: <http://example.org/ns/besocial/data#>

SELECT DISTINCT ?seed ?seedVersion
WHERE {

  # harvests can only be distinguished from other activities based on their name
  ?harvest a prov:Activity ;
           dc:title ?harvestName ;
           prov:used ?seedCollection .

  FILTER ( strStarts(?harvestName, "Harvest") ) .

  # seed versions can only be identified because they are members of harvests
  ?seedCollection a prov:Collection ;
                  prov:hadMember ?seedVersion .

  ?seedVersion prov:specializationOf ?seed .

}
