PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcmitype: <http://purl.org/dc/dcmitype/>
PREFIX ebucore: <https://www.ebu.ch/metadata/ontologies/ebucore#>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX bsd: <http://example.org/ns/besocial/data#>

SELECT ?choVersion ?mimeType ?name
WHERE {

  ?aggregationVersion a edm:Aggregation ;
                      edm:aggregatedCHO ?choVersion ;
                      edm:hasView ?representationVersion .

  ?choVersion a dcmitype:Collection ;
              prov:specializationOf ?cho .

  ?representationVersion a edm:WebResource ;
                         dc:title ?name ;
                         ebucore:hasMimeType ?mimeType .

}
