PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcmitype: <http://purl.org/dc/dcmitype/>
PREFIX ebucore: <https://www.ebu.ch/metadata/ontologies/ebucore#>
PREFIX premis: <http://www.loc.gov/premis/rdf/v3/>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX bsd: <http://example.org/ns/besocial/data#>

SELECT DISTINCT ?seedVersion ?harvestStart ?file ?representationVersion ?representation ?cho
WHERE {

  ?file a premis:File ;
        prov:wasGeneratedBy ?harvest ;
        dcterms:isPartOf ?representationVersion .

  ?representationVersion a edm:WebResource ;
                         prov:specializationOf ?representation .

  ?aggregation a edm:Aggregation ;
               edm:aggregatedCHO ?cho ;
               edm:hasView ?representation .

  ?cho a dcmitype:Collection .


  ?harvest a prov:Activity ;
           dc:title ?harvestName ;
           prov:startedAtTime ?harvestStart ;
           prov:used ?seedCollection .


  ?seedCollection a prov:Collection ;
                  prov:hadMember ?seedVersion .

  ?seedVersion prov:specializationOf ?seed .

}
